### ISSUE TITLE
v 1.3 - unread notification not working

### ISSUE THREAD

**Issue by jchhenderson** [joelekstrom/fastmate#12]
Hi,

Just downloaded this, but cannot get notifications to work.  I have set it in preferences and its OK in settings.

cheers,
J.

**Comment by jchhenderson** [comment]
agh, had to set it also in Fastmail manually (the setting in the app didn't change Fastmail's settings).

I got a notification in the notification screen, but not on there app icon itself though.

**Comment by joelekstrom** [comment]
Hey! Thanks for reporting. Notifications are not exactly related to the badge you see on the app icon - you get notifications depending on your settings for Fastmail (Fastmate will simply display these notifications in the notification centre). 

The badge is only related to the _Fastmate_ settings and shows the unread count of the folders of your choice.

Have you encountered a case where you expect a badge but didn't see one? Could you let me know your Fastmate settings for the badge?

**Comment by jchhenderson** [comment]
Hi,

yes, I have had unread mail but with no badge icon.

I have:
"show unread mail indicator" checked
"in dock" checked
"inbox" checked.

**Comment by jchhenderson** [comment]
huh.  now it correctly showed an unread mail, but it is now read yet the badge still shows unread.  I am not sure it is updating properly.

**Comment by jchhenderson** [comment]
OK, I think it may be do do with my naming "inbox" with a small "I".  I just changed it to a capital "I" and it seems to work now 👍

**Comment by joelekstrom** [comment]
Cool! Maybe I should consider making it case insensitive...

**Comment by jchhenderson** [comment]
nah, I think it is best to keep it as it is as FM's folders are case sensitive (I just made two identical ones except for a capital letter).

Hey, by the way - this is a great app!! :-)

**Comment by joelekstrom** [comment]
Yeah that's true. Thank you! Let me know if you find anything else that doesn't work as expected!
