### ISSUE TITLE
Forked with new features

### ISSUE THREAD

**Issue by mdbraber** [joelekstrom/fastmate#14]
Hi Joel,

Thanks for writing Fastmate - it's excellent and I use it daily since Fluid became less dependendable as a Site Specific Browser. I did miss some features and spotted some bugs. Once I start hacking though there were quite some things I added, so I forked your repository and added them there. Happy to merge them if you're interested!

https://github.com/mdbraber/fastmate/commit/2d58e7af73c56962b35ede71796c3f45909fd338

Features added:
- Applescript support (get url, title, run JavaScript)
- Separate compose window
- Colorize mailbox labels
- Download support within the app
- Quick shortcuts for labels (JS)

And some minor bugfixes (e.g. beta support for downloading)

**Comment by joelekstrom** [comment]
Hi! Thanks for using Fastmate! 😊

Yes, I'll happily accept contributions! If it's not too much trouble, I just ask that you separate each feature into separate PRs.

Thoughts:
* **AppleScript**: Sounds great!
* **Separate compose window**: This sounds like a great feature that I would like myself. I do think it should be a setting in the Fastmail settings window though - so consider adding that (or submit a PR with what you have and I can add it)
* **Colorize mailbox labels**: I believe Fastmate should stay as close to the vanilla Fastmail-experience as possible - so while I'm not against it per se it should go behind a setting if you want to merge it.
* **Download support within the app**: Sounds great!
* **Quick shortcuts for labels**: Sounds great!
* **Bug fixes**: Always keep those coming!

**Comment by mdbraber** [comment]
Thanks for your feedback. I'll try and see if it's easy / possible to separate the features into separate PRs. If you have any pointers for doing that I'd welcome that (as e.g. the Storyboard has now already changed a bit, so not sure how to separate that again for separate PRs). Any help on bringing the changes over to your repository are appreciated.

Colorize mailbox labels is already a separate setting, I'll add one for the Separate compose window too, as well as the Quick Shortcuts for Labels (which is a JS feature).

**Comment by joelekstrom** [comment]
Ah I see. Yeah I'll have to take a close look at the code and see how to separate that when I get the time. But one way to get started is to try separate each feature into a single commit each. An easy way to get started with that would be to do something like this:

1. Soft reset your commits so all your changes are in the worktree
```
git reset --soft 150ebcb4f58732ca42020754e5c81500d972f99a
```

2. Pick a feature that you want to make a commit for, let's say "colorize mailbox labels"
3. Start an interactive stage:
```
git add -p
```

4. Answer `y` for all hunks that are related to this feature, and `n` for the rest
5. Commit these changes
```
git commit -m "Add support for colorizing mailbox labels"
```

6. Repeat from step 2 for the rest of the features.

This normally works fine for the storyboard as well, you can commit smaller parts of it. To verify that each commit works in isolation you could `git stash` after each commit, try compiling, and then `git stash pop` after.

**Comment by mdbraber** [comment]
Thanks for the tips - I'll take a look at those. 

Problem is mostly I've been developing this locally without the idea first that I would fork the repository, so it's currently without any separate commits. Maybe I'll find the time to separate my features and 'redo' as separate PRs. Would be great if you could take a look at my repository, maybe suggest some ideas / improvements and then I can manually start re-adding them as separete PRs to your repository.

**Comment by joelekstrom** [comment]
Hi again @mdbraber!

I've looked through your code.  I posted a comment about the file downloading part (this is my favorite feature so I really think we should try to get this merged). All in all it the code looks good! The file downloading function could probably be simplified a bit but we can discuss that if you can make a PR for it. In any case, I'd like to merge all your features except the following:

- **Separate compose window**: I think I will implement this as part of solving #20 (multi-window support) which will incorporate the change anyway, so I don't think any merging is needed. I really like the shortcut idea so I'll make sure to add that as well 😊
- **Colorize labels**: the reason I think we should exclude this is that Fastmail has added label support in beta which already supports colorization, so I think Fastmail is solving this for us (unless I misunderstood and your code solves a different problem).

Thoughts?

**Comment by mdbraber** [comment]
Excellent. What would you recommend as the best suggestion for merging? I'm no expert coder, so feel free to suggest what's best to do here.

Colorize labels is a personal feature that colors message items with a background color similar to the label (so the message item in the message list is colored). It can certainly be left out as it's a highly personal feature (I can make my own branch for that).

**Comment by joelekstrom** [comment]
I see - here's a suggestion for solving your label color issue. I think we we should add user script support anyway, and it feels like that would solve the problem, right? For example if Fastmate supported that you add a folder containing .js-files which it will run - then everyone can customize CSS/JS for personal features without having to touch the Fastmate code. Would that solve your problem?

As for merging the rest, here's what I think you should do: make a new branch from the current master of this repo. I did some pretty large changes yesterday, including adding a KVOBlockObserver class which you should use for observing titles etc. Then copy the code you want to merge into that branch. Make one commit for each "feature", and then you can make a single pull request from that branch and we can review it all as in one PR.

**Comment by joelekstrom** [comment]
User scripts were added in 1.5.0 so you can try out your custom scripts/CSS with that feature!

**Comment by metbril** [comment]
I just noticed that downloading only works half.

I received an email with multiple images. I can click the image to open it inside the app. So far so good. Clicking the dowbload button directly from the email opens the file in the default browser. Also OK. But when I click the link to download all files at once (as a zip) nothing happens. Is this included in the PR or would you prefer a separate issue?

**Comment by joelekstrom** [comment]
@metbril That doesn’t sound too good. I’d appreciate if you could make a new issue for it, maybe with a screenshot for which button it is that doesn’t work!

**Comment by metbril** [comment]
See #29
