### ISSUE TITLE
Local notifications no longer working(?)

### ISSUE THREAD

**Issue by joelekstrom** [joelekstrom/fastmate#16]
Will need to look into why the JS hook for web notifications no longer fires.

Does anyone else have the same issue?

My current theory is that since Catalina, WKWebView is more aggressive about pausing when in the background

**Comment by posguy99** [comment]
It doesn't work in Mojave either.

**Comment by joelekstrom** [comment]
@posguy99 Thanks! I'll have to look into this

**Comment by joelekstrom** [comment]
@posguy99 If you have the time I'd appreciate if you could try out [v1.4.1](https://github.com/joelekstrom/fastmate/releases/tag/v1.4.1) and see if the issue is resolved!

**Comment by posguy99** [comment]
No, notifications still do not work on 10.14.6 when using Fastmate 1.4.1.

--
Marc Wilson
posguy99@gmail.com

**Comment by posguy99** [comment]
Ok, cancel that.  I did not realize that www.fastmail.com actually maintains the Notification settings separately for different browsers.  I'd set the option from a Safari instance, but when I went to the Fastmail settings menu from inside Fastmate, they were unset again.

Setting them there, then testing them, was successful.

So it's all good.

**Comment by joelekstrom** [comment]
Great! Thanks for checking. Yeah the part with having to enable it again in Fastmail settings is a problem... should maybe make some onboarding for that in Fastmate somehow...
