### ISSUE TITLE
Change the app icon?

### ISSUE THREAD

**Issue by posguy99** [joelekstrom/fastmate#18]
Can you make it possible to change the app icon?  This low-contrast icon is really bad.

<img width="80" alt="2020-04-09-16-25-52" src="https://user-images.githubusercontent.com/408644/78948927-d23e7d00-7a7e-11ea-8ff9-32a0a9dd3a50.png">

**Comment by joelekstrom** [comment]
I won't add support for it within Fastmate itself but it's pretty easy to do yourself: https://9to5mac.com/2019/01/17/change-mac-icons/

Also, that's a pretty cool icon, did you make it? 😄

**Comment by posguy99** [comment]
No, it's from this post.

http://www.emaildiscussions.com/showpost.php?p=562829&postcount=13

**Comment by joelekstrom** [comment]
No offense taken! I'm very much not a designer and I don't think it works well in dark mode. Anyway, I'll close the issue for now since you can probably solve it 😊

**Comment by joelekstrom** [comment]
@posguy99 i made a new attempt at an icon that will go out with the next version (hopefully within a day or two). It matches the new Fastmail design a lot better and I think it looks pretty good both against light and dark docks! Let me know if you like/hate it 😅

https://github.com/joelekstrom/fastmate/blob/master/Fastmate/Assets.xcassets/AppIcon.appiconset/fastmate-256.png

**Comment by posguy99** [comment]
It's a cool icon, but it's still too dark for me.   Not something I would use. ¯\_(ツ)_/¯

**Comment by joelekstrom** [comment]
That’s all right - good that it’s still easy to customise!
