### ISSUE TITLE
Change Window Title Bar

### ISSUE THREAD

**Issue by posguy99** [joelekstrom/fastmate#19]
Is there an opportunity to change the window chrome to match the rest of the system, vs it trying to follow the Fastmail theme that's selected?  It's difficult to pick the window up to move it.

Thanks!

**Comment by joelekstrom** [comment]
Yes, it should be easy to add a setting for that. I'll look into it!

**Comment by joelekstrom** [comment]
Fixed in [v1.4.2](https://github.com/joelekstrom/fastmate/releases/tag/v1.4.2)

**Comment by posguy99** [comment]
W00t!  Thanks.

**Comment by posguy99** [comment]
Can it populate the title bar?  Right. now it's blank.

**Comment by joelekstrom** [comment]
Could you elaborate? Do you want some title text to show up? In that case - what do you expect to see? "Fastmate", or the title of the current e-mail, or something?

**Comment by posguy99** [comment]
Like what fastmail.com populates tab titles with.

![2020-04-11-07-35-42 image](https://user-images.githubusercontent.com/408644/79046686-47b56500-7bc7-11ea-9359-319a2a30c141.jpg)

**Comment by joelekstrom** [comment]
Sure. I can add that - it makes a lot of sense especially if I implement a multi-window workflow

**Comment by joelekstrom** [comment]
@posguy99 Title is added on the master branch and will go out with the next version when I decide to release that. Could be a couple of days so until then you can get it if you compile and run the master branch yourself

**Comment by joelekstrom** [comment]
Title now shows in [v1.5.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.5.0), thanks for the suggestions!
