### ISSUE TITLE
Show link URL on hover

### ISSUE THREAD

**Issue by harbortype** [joelekstrom/fastmate#21]
Would it be possible to show some sort of status bar when hovering links like in browsers? This would be very helpful for identifying phishing emails.

**Comment by joelekstrom** [comment]
Thanks for the request! Yes, this should be possible and is something I would like myself so I’ll look into it when I have time.

**Comment by joelekstrom** [comment]
Added in [v1.5.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.5.0)
