### ISSUE TITLE
Feature request: Run Multiple Instances

### ISSUE THREAD

**Issue by jchhenderson** [joelekstrom/fastmate#22]
Hi,

This app is awesome - thanks for making it available to us :-)

Would it be possible to run multiple instances so I could check on 2 separate Fastmail accounts at the same time (without having to switch-user)?

**Comment by joelekstrom** [comment]
Hi! Thanks again for using it and posting issues/feature requests 😊

Hmm, that's an interesting problem. Currently not possible. I'm investigating adding multi-window support though (#20), so _maybe_ it could be part of that somehow, if one was able to pick a "profile" for each window which chose a separate cookie storage. It brings some other problems though, for example which unread count to show in the dock etc. I'll think about it but right now I'd say given the complexities I probably won't make it top priority. Sorry! I'll happily accept contributions if you or someone else can come up with a nice solution for it. Also if there are more people that needs it I'll make sure to prioritize accordingly!

**Comment by jchhenderson** [comment]
No worries and thanks for even thinking about it 😀
