### ISSUE TITLE
User script support

### ISSUE THREAD

**Issue by joelekstrom** [joelekstrom/fastmate#23]
As discussed in #14, some customizations can be added by users without having to change the Fastmail code if we hade user script support.

My current idea is to allow selecting a folder in the settings view and Fastmate will add any .js-files inside that folder.

**Comment by posguy99** [comment]
How about custom CSS?  I use something that flattens out what fastmail.com prints, so that you're not trying to print silly gray-scales on non-color printers, underlines links, etc.  I know almost nothing about CSS, so it's just experimenting.

**Comment by joelekstrom** [comment]
CSS can be added via JS but I could also make it do that for you if it finds .css files in the user script folder I suppose
