### ISSUE TITLE
v1.5.0 is not a signed app?

### ISSUE THREAD

**Issue by posguy99** [joelekstrom/fastmate#24]
macOS 10.14.6 complains that v1.5.0 is by an unidentified developer.

**Comment by joelekstrom** [comment]
Thanks - I assumed the previous versions had the same problem, has this changed? I’ll look into what I need to do to fix it

**Comment by joelekstrom** [comment]
Just an update here - this is because I don't pay for a personal developer account. I'll consider it... some day 😄. But I assume this has always been a problem even before 1.5.0

**Comment by joelekstrom** [comment]
@posguy99 From 1.8.0 and onward, app is now signed and notarised.
