### ISSUE TITLE
Automatic Dark mode

### ISSUE THREAD

**Issue by christianhans** [joelekstrom/fastmate#25]
Is it possible to enable some kind of Dark Mode based on the MacOS System Setting? I see Fastmail itself has a Dark Theme but I am also thinking about just injecting a few CSS rules when macOS is set to "Dark Appearance".

**Comment by joelekstrom** [comment]
Hmm, if you're thinking about going the CSS route, I recently added user script support (in Fastmate settings). I think you can add special CSS for system dark mode there.

As for an automatic mode, I will not add support for that, but if Fastmail adds that to their website then it should start working automatically (I hope)

**Comment by pro-sumer** [comment]
@christianhans Would you mind sharing your CSS rules?

I would love to have (automatic) dark mode in Fastmail/Fastmate!

**Comment by christianhans** [comment]
Sorry, I don't have any rules. :-) This was just an idea.

**Comment by pro-sumer** [comment]
Fastmail introduced Dark Mode as a beta today...

And it seems to work out of the box when using beta.fastmail.com in Fastmate!

Thank you @joelekstrom (for supporting beta and hence Dark Mode)

**Comment by joelekstrom** [comment]
Great to hear! Thanks for the update 😊
