### ISSUE TITLE
request: Option to print without email headers

### ISSUE THREAD

**Issue by jchhenderson** [joelekstrom/fastmate#26]
Hi there,

Often I am printing an email to pdf because it is a receipt for a purchase.  In this case I do not want the email headers at the start of the print as it moves the receipt down and splits not over 2 pages.

Is it possible to have an option to not print the email headers with the email itself?

cheers,
James.

PS: thanks for making an awesome app free :-)

[edit: typo in heading and added "PS"]

**Comment by joelekstrom** [comment]
Hi, thanks for your request and for using Fastmate 😊

The print layout is defined by Fastmail and is not modified by Fastmate. I think you should send this feedback to Fastmail instead, because if they fix it/add an option for it that will for in Fastmate as well.

**Comment by jchhenderson** [comment]
agh, OK - thanks!
