### ISSUE TITLE
Any chance of getting "mailto:" links?

### ISSUE THREAD

**Issue by saud-kh** [joelekstrom/fastmate#27]
This app is a god send, thank you for all the hard work. I think this feature is basically the only thing missing from it. Keep up the great work!

**Comment by joelekstrom** [comment]
Thanks for using Fastmate!

The app already supports mailto-links. To enable it, you have to open the Apple Mail app, go its settings -> General, and set Fastmate as your default e-mail application.

Let me know if it doesn’t work or if I misunderstood the request!

**Comment by saud-kh** [comment]
it works! thank you. sorry i had no idea how to do that.

**Comment by joelekstrom** [comment]
I should probably add that in the readme or help section or something. Clearly not obvious!
