### ISSUE TITLE
Dowloading all attachments at once fails

### ISSUE THREAD

**Issue by metbril** [joelekstrom/fastmate#29]
Clicking an individual attachement downloads it using the default browser.
Clicking the link to download all attachments at once in a zip file does nothing (nothing happens). 
See attached screenshot and screen recording.

<img width="565" alt="Schermafbeelding 2021-01-16 om 09 59 08" src="https://user-images.githubusercontent.com/559346/104807776-be7c3000-57e1-11eb-8fa4-7b4bf7680ce5.png">

https://user-images.githubusercontent.com/559346/104807669-e0c17e00-57e0-11eb-82c1-9cde5f495f65.mov

**Comment by joelekstrom** [comment]
Thanks for reporting! I’ll try take a look at this within the week.

**Comment by joelekstrom** [comment]
Fixed in [1.6.3](https://github.com/joelekstrom/fastmate/releases/tag/v1.6.3), thanks again for reporting!

**Comment by metbril** [comment]
I've tested it with the earlier message and can confirm that it's working now. Thanks.
