### ISSUE TITLE
App badge only counts unread messages in the current folder

### ISSUE THREAD

**Issue by jacopo-j** [joelekstrom/fastmate#30]
Hi there,

I just noticed that the unread message badge over the app icon does not take into account messages in folders other than the one that is currently selected in the left sidebar (subfolders are also not included).

Since I extensively use message categorization into different subfolders, this is quite unfortunate as I almost never get a correct unread message count.

Are there any chances this could change? Thanks.

**Comment by jacopo-j** [comment]
Sorry, my fault. I didn't notice an option was available in the app Preferences. You can delete this issue :)

**Comment by joelekstrom** [comment]
Thanks for reporting, and great to hear that you found a solution 👌
