### ISSUE TITLE
No sounds on notifications

### ISSUE THREAD

**Issue by tom79** [joelekstrom/fastmate#33]
Your app is excellent and I commend you on creating it. I only wish I'd found it earlier!

There is one issue I've discovered and it's that despite enabling notifications and receiving a banner alert for new emails, there is no sound despite the "Play sound for notifications" box being checked in System Preferences/Notifications. While the macOS notification system does support the playing of sounds, I believe the issue is that your app needs to "provide" a sound to the operating system. I get sound notifications for all my other apps with no problem.

Aside from this, the app is excellent and frankly I don't know why Fastmail themselves haven't created an official version. I really dislike using web/browser-based apps particularly for something as frequently used as email. Your wrapper is a very neat solution to what is an excellent email provider and an excellent web interface. Thank you!

EDIT : I am using the latest version of macOS Big Sur, version 11.2.1, in case that is helpful.

**Comment by joelekstrom** [comment]
Hi! Thanks for the report, and sorry for the slow response! I’ll take a look at this.

I’m glad you’re enjoying Fastmate! Thanks for using it 😊

**Comment by joelekstrom** [comment]
Hi again, this was a total oversight on my part. I forgot to add the sound flag when adding support for the "modern" notification system used on 10.14+. 😅 Fixed in [v1.6.5](https://github.com/joelekstrom/fastmate/releases/tag/v1.6.5)

Thanks again for the report!

**Comment by tom79** [comment]
Thanks so much for fixing this! Hopefully it wasn’t too difficult to solve :-)

Tom

**Comment by joelekstrom** [comment]
It was a whopping single line of code added!
