### ISSUE TITLE
Homebrew distribution

### ISSUE THREAD

**Issue by wmorrel** [joelekstrom/fastmate#36]
Thanks for making Fastmate! I find it super useful.

Have you considered distributing it via [Homebrew](https://brew.sh/)? This may increase audience and would make it easier to keep the app up-to-date for anyone who already has Homebrew in their workflow.

Adding the project into [Homebrew-cask](https://github.com/Homebrew/homebrew-cask) might be the most appropriate way of going about it.

**Comment by joelekstrom** [comment]
Hi! Thanks for the suggestion, and sorry for the slow response! 

The thought has crossed my mind but I haven’t looked into it. Not sure how well Homebrew Cask works with unverified binaries such as this one. I guess it’s just a matter of me reading up on the documentation 😬

**Comment by joelekstrom** [comment]
Hi again! I've checked a bit closer, and Fastmate isn't cool enough to be a cask, unfortunately. 😂 The rules are [here](https://github.com/Homebrew/brew/blob/HEAD/docs/Acceptable-Casks.md#rejected-casks).

> The Cask is for an app that is too obscure. Examples:
An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

**Comment by rajiv** [comment]
I've created a homebrew tap for Fastmate. See [rajiv/homebrew-fastmate](https://github.com/rajiv/homebrew-fastmate) and #45.
