### ISSUE TITLE
Question: Can I run two incidences of Fastmate (for different Fastmail Accounts)?

### ISSUE THREAD

**Issue by jchhenderson** [joelekstrom/fastmate#37]
as per the question.

Can I run two incidences of Fastmate (for different Fastmail Accounts)?

This is so I can get notifications from each Fastmail account without having to user-switch to do it.

cheers,
James.

**Comment by joelekstrom** [comment]
Hi, sorry for the late answer. This is unfortunately not supported and likely won’t be 😞

**Comment by jchhenderson** [comment]
no worries - it's still awesome!

**Comment by joelekstrom** [comment]
Thanks for using it! 😊
