### ISSUE TITLE
Icon BigSur Style

### ISSUE THREAD

**Issue by melvinsalas** [joelekstrom/fastmate#39]
I really like FastMate, it is a very good product.

Is it possible to change the dock icon to more BigSur style, i.e. square and round instead of circular?

Because, it doesn't match on dock

<img width="554" alt="CleanShot 2021-05-19 at 09 47 34@2x" src="https://user-images.githubusercontent.com/708747/118843405-43a64d00-b887-11eb-8651-f1c41195e129.png">

Thanks :D

**Comment by joelekstrom** [comment]
Hi! Thanks so much for using Fastmate 😊 

you’re right - I should probably have a go at de-rounding the icon. I’ll put it on my todo list!

**Comment by sddgit** [comment]
Here's one for your consideration. I think it's in the correct format.

[icon.icns.zip](https://github.com/joelekstrom/fastmate/files/6614060/icon.icns.zip)

**Comment by joelekstrom** [comment]
Hi @sddgit and thanks for the icon! Since it's the official logo I can't put that in the build - but it's nice to keep here if anyone wants to manually use that icon on their own Fastmate installation.

**Comment by sddgit** [comment]
OK, no problem.

**Comment by melvinsalas** [comment]
I worked on this one (the third), what do you think?

<img width="887" alt="CleanShot 2021-06-08 at 13 20 24@2x" src="https://user-images.githubusercontent.com/708747/121244624-52679a80-c85c-11eb-8e5c-74102ad92d6a.png">

**Comment by sddgit** [comment]
I think that looks pretty good. Could you try the 3-colour envelope on the blue background for comparison?

**Comment by melvinsalas** [comment]
Sure!

<img width="877" alt="CleanShot 2021-06-08 at 20 42 32@2x" src="https://user-images.githubusercontent.com/708747/121284434-14896700-c89a-11eb-8392-b6a3559b6b19.png">

**Comment by sddgit** [comment]
Great! Any chance of uploading those four in icon format to try in real life?

**Comment by melvinsalas** [comment]
I converted png to .ico files.
Let me know if you need it a change or if you want the adobeXD file.

[iconpack.zip](https://github.com/joelekstrom/fastmate/files/6620998/iconpack.zip)

**Comment by sddgit** [comment]
I can’t use the icons for the Fastmate app. I'm really not sure of the technical aspects of icons. When I click on one of your icons in Finder, it says it's a Windows icon file. The icon I have has a .icns extension, and is identified as an Apple icon image. Dragging one of your icons to the icon area of the Info window of Fastmate doesn't work - I just get a generic icon for the app.

**Comment by melvinsalas** [comment]
Can you try these?

[icnspack.zip](https://github.com/joelekstrom/fastmate/files/6625096/icnspack.zip)

**Comment by sddgit** [comment]
They're actually a little big. I’ve attached some screenshots of the dock, and screenshot of the properties of the Apple Mail icon.
<img width="63" alt="Screen Shot 2021-06-10 at 10 52 08 am" src="https://user-images.githubusercontent.com/76281052/121448536-376f6480-c9db-11eb-8c61-d2b75bcaa5d3.png">
<img width="63" alt="Screen Shot 2021-06-10 at 10 52 40 am" src="https://user-images.githubusercontent.com/76281052/121448539-39d1be80-c9db-11eb-882c-e87dd823e3a9.png">
<img width="628" alt="Screen Shot 2021-06-10 at 10 57 33 am" src="https://user-images.githubusercontent.com/76281052/121448542-3a6a5500-c9db-11eb-8de3-ba4d0d546137.png">

On a dark background, I think the "white" versions look better, but depart from the original quite a lot, so might not please the author as much! Rounded matches the Apple Mail icon better. Getting picky, but maybe a lighter blue background?

**Comment by melvinsalas** [comment]
I'm just playing about the design, I work on this. [icon design.icns.zip](https://github.com/joelekstrom/fastmate/files/6649393/icon.design.icns.zip)

<img width="421" alt="CleanShot 2021-06-14 at 09 08 10@2x" src="https://user-images.githubusercontent.com/708747/121915192-39de0100-ccf0-11eb-9167-a33636d6ccf7.png">

**Comment by sddgit** [comment]
That looks really nice - well done, and thank you! Let's see if it gets picked as the "official" icon.

**Comment by joelekstrom** [comment]
Hey @melvinsalas I really like the open one! The top one is a bit too close to the Apple one IMO. Perhaps the background color should change slightly too so it's not too close

Also, sorry for taking so long to respond, have had a lot of stuff going on lately.

**Comment by melvinsalas** [comment]
Don't worry.

Something like that?

<img width="910" alt="CleanShot 2021-06-23 at 12 11 30@2x" src="https://user-images.githubusercontent.com/708747/123147357-2895a280-d41c-11eb-8471-27cc70a74c1c.png">

**Comment by joelekstrom** [comment]
Yeah that looks pretty great to me! I'm not sure about the vertical centering - should it be moved up a bit? 🤔 I really appreciate the efforts btw.

To make it available in the Fastmate build, I'll need it in 3 different sizes: 1024x1024, 512x512 and 256x256. If you provide a 1024 I can scale that down too.

**Comment by woodjosiah** [comment]
This seems like it stalled out a bit ago. I've really enjoyed using @melvinsalas design, so I recreated it in Sketch. I'll admit it's not perfect, so I'm including the Sketch file so someone else can tweak it more if they'd like. If this helps the icon to be updated to be Big Sur/Monteray style in a future build, awesome! No worries if you want to go in a different direction.
![icon@256](https://user-images.githubusercontent.com/6176118/152274357-16091e60-1d72-4cdf-bce5-aafe0b8dd960.png)
![icon@512](https://user-images.githubusercontent.com/6176118/152274358-e2dce1b9-e7e8-471f-a87b-d533c15aaadb.png)
![icon@1024](https://user-images.githubusercontent.com/6176118/152274360-cfc652ae-6a9b-4bff-aa4b-262aa819e843.png)
[Fastmate Icon Sketch.zip](https://github.com/joelekstrom/fastmate/files/7991509/Fastmate.Icon.Sketch.zip)

**Comment by joelekstrom** [comment]
@woodjosiah Thank you very much! 🙌 Looks pretty great to me, I'll try that out ASAP.

**Comment by joelekstrom** [comment]
@woodjosiah Tried it out and will likely ship it with the next update! However, I think it needs some additional margins to match the size of xcode, safari etc, as you can see in the bottom of the screenshot. Apple has published a Sketch library for macOS where I imagine you could find a template for sizes maybe? https://developer.apple.com/design/resources/
 
<img width="145" alt="Skärmavbild 2022-02-09 kl  19 48 22" src="https://user-images.githubusercontent.com/1607453/153269376-8a06b3a6-0dee-4b5d-ac83-f920d023ca32.png">

**Comment by woodjosiah** [comment]
@joelekstrom Oops, I had 'trim transparent pixels' turned on in Sketch. Try the attached ones instead
[Fastmate Icons.zip](https://github.com/joelekstrom/fastmate/files/8035461/Fastmate.Icons.zip)
.

**Comment by joelekstrom** [comment]
Awesome, thank you! Looks great 😊

**Comment by melvinsalas** [comment]
Oh, sorry, I forgot to respond.
Anything I can help with the logo, I'm also available.
;)

**Comment by joelekstrom** [comment]
@melvinsalas of course, you could give your blessing that I ship the icon from @woodjosiah? It's your design after all! (I'll properly attribute you both in the update notes).

Looks like this btw!
<img width="171" alt="Skärmavbild 2022-02-09 kl  21 20 24" src="https://user-images.githubusercontent.com/1607453/153283535-ac8c47b7-7fdc-4dc0-8499-ddc181b8d6b7.png">

**Comment by melvinsalas** [comment]
Thanks @woodjosiah and @joelekstrom 
Thanks for your support in this forgotten ticket.
Let's hope that this new design will prosper.

**Comment by joelekstrom** [comment]
Added and will be out with the next version! @woodjosiah if you would like to share it it would be nice if you could add the Sketch files to this repo, making the icon also available as open source and tweakable in the future

**Comment by woodjosiah** [comment]
@joelekstrom Totally! It’s actually included in my original comment, it’s the attachment labeled “Fastmate Icon Sketch.zip".

**Comment by joelekstrom** [comment]
If you upload it here to the root folder (name it `icon.sketch` for clarity) via a PR, GitHub will list you as a contributor to the repo

<img width="935" alt="Skärmavbild 2022-02-10 kl  13 47 17" src="https://user-images.githubusercontent.com/1607453/153411657-0fdcd432-16d1-4a49-9866-f1839d890601.png">
