### ISSUE TITLE
App doesn't remember width and height when quitting

### ISSUE THREAD

**Issue by christianhans** [joelekstrom/fastmate#4]
Seems to always open with 200px width and 100px height on app launch - regardless of previous window resizing

**Comment by accatyyc** [comment]
Thanks for reporting! I've seen this issue reported before, and there's code to keep the size (and it works for me), so I'm not sure why it doesn't work for some people.

Could you tell me which OS version you're running - and also which app version? (Menu bar -> Fastmate -> About Fastmate)

**Comment by accatyyc** [comment]
Actually - I may know what's causing this. Try going to System Preferences -> General, do you have the `Close windows when quitting an application` box ticked?

I think that might cause the behaviour.

**Comment by christianhans** [comment]
Yes, I had that box checked. Disabling this setting works as a workaround. Is there a fix so I can leave this option enabled?

**Comment by accatyyc** [comment]
Yeah, I suppose I could store the state manually. I'll think about it

**Comment by joelekstrom** [comment]
Fixed in [1.0.5](https://github.com/joelekstrom/fastmate/releases/tag/v1.0.5)
