### ISSUE TITLE
Can't print a PDF attachment

### ISSUE THREAD

**Issue by sddgit** [joelekstrom/fastmate#40]
First up - oh man, where have you been?! I just saw Fastmate referenced in the Fastmail subreddit, and I'm overjoyed...

One problem I’ve come across - if I click on a PDF attachment, it opens and shows the contents, but when I try to print it, the preview and resulting print just shows a blank page. Is this a known restriction?

Thank you for a terrific product.

**Comment by joelekstrom** [comment]
Thanks for the bug report (and yeah, I saw the threads, feels good 😄). I'll look into it! (and sorry for the slow answers)

**Comment by sddgit** [comment]
Great - thank you!

**Comment by joelekstrom** [comment]
Fixed in [v1.6.6](https://github.com/joelekstrom/fastmate/releases/tag/v1.6.6)

**Comment by sddgit** [comment]
I can’t see a binary for V1.6.6. Should it be there?

**Comment by joelekstrom** [comment]
Whoops, good catch 😅 fixed now!

**Comment by sddgit** [comment]
Thank you!

**Comment by sddgit** [comment]
Works beautifully - thank you!
