### ISSUE TITLE
Open Fastmail login page at start (when not logged in)

### ISSUE THREAD

**Issue by pro-sumer** [joelekstrom/fastmate#41]
Since I tend to log out from Fastmail every evening on my work Mac, I need to log in again the next morning. Recently I have been getting a generic Fastmail (home) page instead of the Fastmail login page (requiring an extra click to go to the login page).

Would it be possible to immediately open https://www.fastmail.com/login/ at start, when not logged in?

**Comment by joelekstrom** [comment]
Hi! That's a great idea. Fixed in the commit above and will release with the next version!

**Comment by joelekstrom** [comment]
Fixed in [v1.6.6](https://github.com/joelekstrom/fastmate/releases/tag/v1.6.6)
