### ISSUE TITLE
Can't print from Fastmate

### ISSUE THREAD

**Issue by iamscott** [joelekstrom/fastmate#5]
No print dialog; hitting print does not do anything.

**Comment by joelekstrom** [comment]
Thanks for the report! I rarely print myself so I haven’t even considered the possibility. I’ll take a look at it!

**Comment by joelekstrom** [comment]
This seems to be a [bug in WKWebView](http://www.openradar.me/23649229), which is what Fastmate uses.

There are some workarounds, but nothing I have time to do in the coming weeks. However - what I can do is make Fastmate open your system browser and forward the print command to that - would that solve your problem?

**Comment by iamscott** [comment]
Sure, it's a pretty rare issue and easy to work around (just open the browser), but I thought I'd add it in the interest of helping other users and making Fastmate more complete. Unless the workaround is a simple fix, it's probably best to just wait until you (or someone else) has time to implement a system print dialog.

**Comment by joelekstrom** [comment]
Yes, I appreciate you finding the stuff I haven't thought about, and this would definitely be a nice quality of life improvement. I'm leaving this issue open for now.

**Comment by posguy99** [comment]
Running Fastmail with Fluid 2.x has this issue, with 1.x it does not.  The author of Fluid called it a signing issue when I reported it.  Not that this is Fluid, but maybe that helps you

I print *often*, so I went back to a Fluid 1.x SSB vice 2.x.

**Comment by joelekstrom** [comment]
Thanks! That’s good information. I’ll take a look at that as well - but most likely it’s because Fluid 2.0 uses `WKWebView` just like Fastmate. It works fine in the older `WebView`, and I’d wager that’s what Fluid 1.0 uses.

I’ve seen some workarounds where an application can create an instance of the deprecated WebView just for printing. I will give that a shot some day

**Comment by joelekstrom** [comment]
This is now fixed and released in [version 1.4.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.4.0). Let me know if it doesn't work!

I decided to go with the "hack" to instantiate the deprecated `WebView` to solve it.

**Comment by jchhenderson** [comment]
v1.4 works great - thanks!

I mostly save my prints as pdf's.  Would it be possible to. have the pdf title default to the email title?

**Comment by joelekstrom** [comment]
Thanks for the update @jchhenderson! 

Regarding PDF's - yes, that should be possible. I'll make a separate issue for it

**Comment by jchhenderson** [comment]
fantastic - thanks!
