### ISSUE TITLE
Zoom the view / font_size?

### ISSUE THREAD

**Issue by johnnyutahh** [joelekstrom/fastmate#55]
Does Fastmate.app offer a means to Zoom (in and out) the view / font_size?

Thanks for making the app!

**Comment by joelekstrom** [comment]
Hi! It does not at the moment, sorry. I'm looking into if I can easily enable it!

**Comment by joelekstrom** [comment]
Fixed in [v1.8.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.8.0), thanks for the request!

**Comment by johnnyutahh** [comment]
Fantastic, thank you @joelekstrom !

Unfortunately, I can't get v1.8.0 to open on my system, and I'm running macOS 10.14.6, so I can't try v1.8.1 either.  :-/

Thanks in any case for driving this project, I do hope to be able to run the app someday.

**Comment by joelekstrom** [comment]
@johnnyutahh Sorry to here that! Could you try the steps here to disable Gatekeeper for Fastmate? That should fix issues with launching the app: https://disable-gatekeeper.github.io/

**Comment by joelekstrom** [comment]
Actually - I notarised a 1.8.0 build, please try that instead:
[Fastmate-1.8.0-notarised.zip](https://github.com/joelekstrom/fastmate/files/7968690/Fastmate-1.8.0-notarised.zip)

**Comment by johnnyutahh** [comment]
Much appreciated. I downloaded and ran the v1.8.0 per below, and it seems to have the same behavior as what I tried a few hours earlier: the app seems to "flash open" (or form what little I can see; some frame pops up for what seems like less than a tenth of a second) and then disappears.

I see no "Allow apps..." Fastmate stuff listed at the `Security & Privacy` settings pref, like I might otherwise expect.

@joelekstrom - I'm happy to try other things, too. I did not yet execute any method/steps/procedure from https://disable-gatekeeper.github.io.

> Actually - I notarised a 1.8.0 build, please try that instead: [Fastmate-1.8.0-notarised.zip](https://github.com/joelekstrom/fastmate/files/7968690/Fastmate-1.8.0-notarised.zip)

**Comment by jcsteele** [comment]
@johnnyutahh follow the instructions in the guide mentioned first if you could...this will rule out any gatekeeper issues firstly.

Disabling Gatekeeper for one application only

Using Finder
    1. Open Finder and navigate to the Fastmate application you just downloaded.
    2. Right-click the application and choose Open.
    3. Click Cancel in the confirmation dialog that appears. 
    4. Right-click the application a second time and choose Open again.
    5. Click Open in the confirmation dialog that appears.

You only have to do this for the first application start. You can start the application as usual afterwards.

**Comment by johnnyutahh** [comment]
I performed the following, a couple times (with the latest .zip download). Same problems.

I can try generally-disabling Gatekeeper later (pls remind me if you can?). For now, I have a growing doubt this is a Gatekeeper-related problem.

**Comment by jcsteele** [comment]
I would agree with your suspicions that this may be another issue.  Where you running the Fastmail.app from?  Downloads?  Applications?

Here are the instructions for globally disabling gatekeeper - please remember to re-enable it after testing.

Disabling Gatekeeper permanently

    Open a terminal by pressing Cmd + Space, enter “Terminal” and open the application.
    Run the following command: sudo spctl --master-disable. Enter your administrator password when requested.
    Gatekeeper is now disabled permanently.

**Comment by johnnyutahh** [comment]
Solved!  Details below. Thanks @jcsteele for your diligent effort, much appreciated.

All the `open` cmds in the following session succeeded. Fastmate.app now runs on my macOS... and supports zooming!  It's a beautiful thing.

**Question**: is running (`Fastmate.app`) with`Gatekeeper=globally_disabled`, then running again `Gatekeeper=globally_enabled` expected to succeed like this? If not, I'd like to invesigate further to see if there possibly something else happening here.

```
$ sudo spctl --master-disable
$ sudo spctl --status
assessments disabled
$
$ open /Applications/Fastmate.app
$
$ cd /Applications
$ sudo mv Fastmate.app/ Fastmate-1.8.0.app
$ cd
$
$ open /Applications/Fastmate-1.8.0.app
$
$ sudo spctl --master-enable
$ sudo spctl --status
assessments enabled
$
$ open /Applications/Fastmate-1.8.0.app
$
$ ls -d /Applications/Fastmate-1.*
/Applications/Fastmate-1.7.0.app  /Applications/Fastmate-1.8.0.app
$
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9323
$
$ date
Mon Jan 31 13:18:10 CST 2022
$
```

**Comment by joelekstrom** [comment]
Well this is interesting, thanks for trying all this stuff. Yes, Gatekeeper enabled _should_ work with the new notarised build so I was very surprised you saw the issue again with that. Was it the same exit code 9 thingy?
