### ISSUE TITLE
Theme changes to light mode

### ISSUE THREAD

**Issue by kashura** [joelekstrom/fastmate#57]
First of all, want to applaud how much Fastmate has improved my workflow. Thank you @joelekstrom !

I'm using FastMail Beta, and after the recent update to Fastmate my these is constantly changing to the light version. Any other reports of whether this is on the client or FM Beta?

**Comment by joelekstrom** [comment]
Hi, thank you 😊

I think this is dependent on your theme settings withing Fastmail itself - if you don't want it to automatically change to light mode you need to turn that functionality off:

<img width="1064" alt="Skärmavbild 2022-01-16 kl  21 26 32" src="https://user-images.githubusercontent.com/1607453/149676815-df335c43-ccf1-4ce8-92d7-7114a6cdeba9.png">

**Comment by kashura** [comment]
Ah, interesting. 

I don't have this toggle in Fastmail inside Fastmate. But I do see this option in beta.fastmail.com and it's not enabled.

**Comment by kashura** [comment]
To wrap up this issue, is it possible to force beta experience in Fastmate? I don't see it mentioned in readme.

**Comment by rajiv** [comment]
@kashura: There is a setting in Fastmate preferences to use beta.

**Comment by kashura** [comment]
Thank you @rajiv . 

Seems to then be an issue with non beta version. Switching to beta has eliminated this issue. I just switched back to regular FM and will keep an eye and see if the issue returns.

In case it helps, I am on Fastmate 1.8.0, and Monterey 12.0.1.

As my issue is resolved, I'm glad to close this or leave it open for a bit to see if the issue returns.
