### ISSUE TITLE
Clicking on notification should open message

### ISSUE THREAD

**Issue by iamscott** [joelekstrom/fastmate#7]
Clicking on notification just opens the app. If possible, it should open the message that is being displayed in the notification.

**Comment by joelekstrom** [comment]
Thanks for the suggestion!

Yes, this should be possible to fix. I'll probably take a look at it some time this month.

**Comment by iamscott** [comment]
Thanks!

**Comment by joelekstrom** [comment]
Fixed in [v1.2.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.2.0)!
