### ISSUE TITLE
Use new Fastmail icon

### ISSUE THREAD

**Issue by pro-sumer** [joelekstrom/fastmate#8]
Today FastMail changed its name to Fastmail and they also have a new (App) icon:

https://fastmail.blog/2019/06/24/fastmail-new-logo/

Can you please update the icon in Fastmate?

**Comment by joelekstrom** [comment]
Thanks for the heads-up! The icon for Fastmate is just something I made that resembled the old Fastmail-logo, so I'd have to make something new. I'll write to them and ask if it's OK that I use the official one as well.

**Comment by pro-sumer** [comment]
Maybe use their new [Twitter avatar](https://twitter.com/fastmail)? (If they allow you to do so)

**Comment by pro-sumer** [comment]
Or the new [iOS icon](https://apps.apple.com/us/app/fastmail-email-calendar/id931370077)?

![iOS icon](https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c4/69/73/c4697361-bf9a-e726-053c-879138320dd4/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-6.png/690x0w.jpg)

**Comment by joelekstrom** [comment]
Yeah, I wrote to them and I'll see if it's OK. I will not use the icon without permission, since it can lead to troubles with takedowns etc.

**Comment by joelekstrom** [comment]
According to the [Fastmail press information](https://www.fastmail.com/about/press/#?logo) rules I’m not allowed to use the official logo, so I’ll have to create another look-alike

**Comment by pro-sumer** [comment]
Understood. I'd rather have this App with a different icon then no App at all.

**Comment by joelekstrom** [comment]
I made a new logo which I think looks pretty good! It’s in the readme here right now, and will be released with the next version, hopefully within a day or two.
