### ISSUE TITLE
Add option to run Fastmail beta

### ISSUE THREAD

**Issue by pro-sumer** [joelekstrom/fastmate#9]
On https://beta.fastmail.com you can already see the new Fastmail UI (see #8).

Perhaps you can add an config option to Fastmate to either use `fastmail.com` or `beta.fastmail.com `?

**Comment by joelekstrom** [comment]
Adding an option to run beta should be fairly simple - but I see that they went live with the new UI already (and it's turning up in Fastmate). Do you still need the option to run the beta version?

**Comment by pro-sumer** [comment]
Ah, I indeed have the new UI now.

Still it might be nice to select/use beta in Fastmate (for example if you beta test for Fastmail, which I have done).

**Comment by joelekstrom** [comment]
Added in [1.3.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.3.0). Thanks for all the issues reported, keep them coming!
