### ISSUE TITLE
Save "zoom" state after close

### ISSUE THREAD

**Issue by openclosure** [joelekstrom/fastmate#92]
First, thanks for the great app, as you note email is a sensitive area and the fact that this app is OSS gives me confidence to use it over alternatives. 

Was wondering if it would be possible to save the state of the zoom or set a default so you don't have to manually toggle it each time the app is closed/reopened.

**Comment by joelekstrom** [comment]
Thank you, I'm glad to hear it!

Yes, this was a pretty easy thing to add. I pushed a commit that added it. Not sure when I will push a new "real" update but feel free to run this beta until then and try it out:
[Fastmate-1.9.1-beta.zip](https://github.com/joelekstrom/fastmate/files/9422018/Fastmate-1.9.1-beta.zip)

**Comment by openclosure** [comment]
🙏 Works perfectly, thank you!
