### ISSUE TITLE
"mailto:" links no longer work

### ISSUE THREAD

**Issue by rajiv** [joelekstrom/fastmate#94]
Hi. I'm not sure when this broke, but running Fastmate 1.9.0 on macOS Monterey 12.6.1 and `mailto:` links from webpages no longer work. 

After clicking on a link on a webpage of the form `<a href="mailto:user@example.com">user@example.com</a>` Fastmate does open to the Fastmail compose window, with a new message. However the "To" field in the message has `@example.com`, or sometimes `er@example.com` or even `example.com`.

This happens with links from the Safari, Chrome, and Firefox.

Possibly related to #95.

**Comment by joelekstrom** [comment]
Thanks for reporting. Seeing the same issue. It feels like this may be a Fastmail problem - Fastmate handles this by opening a URL such as https://app.fastmail.com/mail/compose?mailto=test@example.com and I'm observing the same behavior when I open this link in browsers.

Interestingly, the above is the exact URL which Fastmail itself registers in Chrome when you set it top open as default e-mail app, and in that case it actually does work correctly

**Comment by joelekstrom** [comment]
I have opened a ticket with Fastmail support to see if this can be fixed on their side

**Comment by rajiv** [comment]
Oh interesting. Clicking this link works correctly: https://app.fastmail.com/mail/compose?to=test@example.com&cc=foo@example.com&subject=A+test+email&body=https%3A%2F%2Fgithub.com%2Fjoelekstrom%2Ffastmate%2Fissues%2F94

Note the `to` instead of `mailto` and the URL encoded subject and body.

**Comment by joelekstrom** [comment]
Ah, nice find! Thank you. I will update Fastmate to use that format

**Comment by joelekstrom** [comment]
Fixed in [v1.9.1](https://github.com/joelekstrom/fastmate/releases/tag/v1.9.1)
