### ISSUE TITLE
Share via email no longer works

### ISSUE THREAD

**Issue by rajiv** [joelekstrom/fastmate#95]
Hi. I'm not sure when this broke, but running Fastmate 1.9.0 on macOS Monterey 12.6.1 and the Safari "Email this page", Chrome "Email link", or Firefox "Email" functions no longer works.

If you navigate to a web page in any of those three browsers, and choose "File > Share > Email" from the menu, Fastmate does open to the Fastmail compose window, with a new message. However the "To" field has just a `t` in it. This share feature used to compose a new message with the webpage Title in the email Subject field, and the URL in the body.

Possibly related to #94.

**Comment by joelekstrom** [comment]
This indeed seems related to #94

**Comment by joelekstrom** [comment]
Fixed in [v1.9.1](https://github.com/joelekstrom/fastmate/releases/tag/v1.9.1)
